[target.riscv32imc-unknown-none-elf]
runner = "espflash flash --monitor --chip esp32c3"
rustflags = ["-C", "force-frame-pointers"]

[target.xtensa-esp32-none-elf]
runner = "espflash flash --monitor --chip esp32"
rustflags = ["-C", "link-arg=-nostartfiles"]

[env]
ESP_LOG = "info"

[unstable]
build-std = ["alloc", "core"]

[alias]
esp32c3 = "run --target riscv32imc-unknown-none-elf --features=esp32c3 -- -p=com4"#
# Das hier muss mit "+esp" ausgeführt werden.
esp32 = "r --target xtensa-esp32-none-elf --features=esp32 -- -p=com3"