M48
; DRILL file {KiCad 8.0.1} date 2025-08-12T22:44:45+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-08-12T22:44:45+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0197
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0315
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0354
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T4C0.0394
%
G90
G05
T1
X4.39Y-1.82
X4.39Y-1.92
T2
X3.31Y-2.35
X3.31Y-2.65
T3
X3.6Y-2.9
X3.7Y-2.9
X3.82Y-2.9
X3.92Y-2.9
X4.04Y-2.9
X4.14Y-2.9
X4.26Y-2.9
X4.36Y-2.9
T4
X5.5Y-1.92
X5.6Y-1.92
X5.6Y-2.7
X5.6Y-2.8
X5.7Y-1.92
X5.7Y-2.7
X5.7Y-2.8
X5.8Y-1.92
X5.8Y-2.7
X5.8Y-2.8
M30
